package modao

import (
	"fmt"

	"github.com/rrzu/modao/common"
	"github.com/samber/lo"
)

type GenImports []string

// ToText 转成展示文本
func (gmc *GenImports) ToText() (str string) {
	for _, s := range *gmc {
		str += s
	}

	return
}

type GenModCols []string

// ToText 转成展示文本
func (gmc *GenModCols) ToText() (str string) {
	for _, s := range *gmc {
		str += s
	}

	return
}

type GenDaoCols []string

// ToText 转成展示文本
func (gmc *GenDaoCols) ToText() (str string) {
	for _, s := range *gmc {
		str += s
	}

	return
}

// SetColumnTyp 设置字段类型
func (t *ModTable) SetColumnTyp(field string, typ string) *ModTable {
	if field == "" {
		return t
	}

	if tblCol, ok := t.columnMap()[field]; ok {
		tblCol.typ = typ
		t.columns[tblCol._index] = tblCol
	} else {
		t.SetColumnField(field)
		t.SetColumnTyp(field, typ)
	}
	return t
}

// columnMap 字段映射
func (t *ModTable) columnMap() map[string]Columns {
	if t.columns == nil {
		t.columns = make([]Columns, 0)
	}

	return lo.KeyBy(t.columns, func(item Columns) string { return item.field })
}

// SetColumnField 设置字段名
func (t *ModTable) SetColumnField(field string) *ModTable {
	if field == "" {
		return t
	}

	if tblCol, ok := t.columnMap()[field]; !ok {
		tblCol._index = len(t.columns)
		tblCol.field = field
		t.columns = append(t.columns, tblCol)
	}

	return t
}

// SetColumnTag 设置字段标签
func (t *ModTable) SetColumnTag(field string, tag string) *ModTable {
	if field == "" {
		return t
	}

	if tblCol, ok := t.columnMap()[field]; ok {
		tblCol.tag = tag
		t.columns[tblCol._index] = tblCol
	} else {
		t.SetColumnField(field)
		t.SetColumnTag(field, tag)
	}
	return t
}

// SetColumnComment 设置字段注释
func (t *ModTable) SetColumnComment(field string, comment string) *ModTable {
	if field == "" {
		return t
	}

	if tblCol, ok := t.columnMap()[field]; ok {
		tblCol.comment = comment
		t.columns[tblCol._index] = tblCol
	} else {
		t.SetColumnField(field)
		t.SetColumnComment(field, comment)
	}
	return t
}

// ToGenModCols 生成 GenModCols
func (t *ModTable) ToGenModCols(req GenModDaoReq) (cols GenModCols) {
	cols = make(GenModCols, 0)

	if t.columns == nil {
		return
	}

	for _, column := range t.columns {
		name := common.UnderScoreToCamel(column.field)
		cols = append(cols, fmt.Sprintf("    %s %s %s // %s\n", name, column.typ, toTag(column.field), column.comment))
	}

	if len(cols) > 0 {
		cols = append([]string{fmt.Sprintf("// %s %s\ntype %s struct {\n", modName(t.tableName), t.tableComment, modName(t.tableName))}, cols...)
		cols = append(cols, "}\n")

		cols = append(cols, createModMethods(req)...)
	}
	return
}

// ToGenImport 生成 GenImport
func (t *ModTable) ToGenImport(GenModDaoReq) (imports GenImports) {
	imports = make(GenImports, 0)
	imports = append(imports, "// Code generated by tool. DO NOT EDIT.\n\n")
	imports = append(imports, "package md\n\n")
	imports = append(imports, "import (\n")
	imports = append(imports, "	\"context\"\n\n")
	imports = append(imports, "	\"github.com/rrzu/modao\"\n")
	imports = append(imports, ")\n\n")

	return
}

// ToGenDaoCols 生成 GenDaoCols
func (t *ModTable) ToGenDaoCols(req GenModDaoReq) (cols GenDaoCols) {
	cols = make(GenDaoCols, 0)

	if t.columns == nil {
		return
	}

	cols = append(cols, createDaoMethods(req)...)
	return
}
